### ISSUE TITLE
[2pt] Setup mobile and desktop version of the app to make it responsive

### ISSUE THREAD

**Issue by akos29** [akos29/book_appointment#11]
- should be responsive, both mobile and desktop versions.

**Comment by mahabubx7** [comment]
check branch: `resposive-design` in frontend repo
I have made big changes

**Comment by mahabubx7** [comment]
@akos29 https://github.com/akos29/book_appointment_front/pull/12
I have completed the responsive design.

![localhost_3000_(iPhone SE) (2)](https://github.com/akos29/book_appointment/assets/122348996/32b2d751-3355-4a06-ae30-fb6b3b032148)
![localhost_3000_(iPhone SE) (1)](https://github.com/akos29/book_appointment/assets/122348996/6e1df3e8-f30c-4c8c-8ed1-71931512d136)
![localhost_3000_(iPhone SE)](https://github.com/akos29/book_appointment/assets/122348996/64c537fd-20ed-40a9-819a-4741c2b7eddc)
![localhost_3000_ (2)](https://github.com/akos29/book_appointment/assets/122348996/9d864850-28cc-4daa-8508-d0549d5cece8)
![localhost_3000_ (1)](https://github.com/akos29/book_appointment/assets/122348996/39dcbd1b-47e9-4970-b1f2-6676aa23d56b)
