### ISSUE TITLE
[2pt] Setup repository - Group Task

### ISSUE THREAD

**Issue by akos29** [akos29/book_appointment#3]
- Set up the repository/repositories on GitHub and use Gitflow.
- Setup Postgres as a database
- Use Rails to create backend API.
- Select how to up the project as two separate apps or as one.
- The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

**Comment by mahabubx7** [comment]
Backend: #16 
Frontend: [#frontend](https://github.com/akos29/book_appointment_front/pull/3)
